apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    run: app-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30060
  selector:
    app: app-server
