apiVersion: apps/v1 

kind: Deployment
metadata:
  name: db-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-server
    spec:
      containers:
      - image: kilokilo8/db:latest
        name: db-server
        
        env:	
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: train
        - name: MYSQL_USER
          value: julien
        - name: MYSQL_PASSWORD
          value: password
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
          name: db-server
